version: '3.8'

services:
  backend:
    image: mysten/zklogin:prover-stable
    platform: linux/amd64
    ports:
      - "5001:8080"
    environment:
      - RUST_LOG=info
      - ZKEY=/app/zkey/zkLogin.zkey
      - WITNESS_BINARIES=/app/binaries
    volumes:
      - ./zkLogin.zkey:/app/zkey/zkLogin.zkey
      - ./zkLogin.zkey:/app/binaries/prod/zkLogin.zkey
    restart: unless-stopped

  frontend:
    image: mysten/zklogin:prover-fe-stable
    platform: linux/amd64
    command: '8080'
    ports:
      - "5003:8080"
    environment:
      - PROVER_URI=http://backend:8080/input
      - NODE_ENV=production
      - DEBUG=zkLogin:info,jwks
      - PROVER_TIMEOUT=45
    restart: unless-stopped 