#!/usr/bin/env python3
"""
build-kinetic-reel.py — assemble a 9:16 "voice + kinetic type" Reel from
interview audio clips and a Whisper word-timestamp JSON.

Pipeline:
  1. Cut each clip from the source audio (short fades), concatenate with gaps
     and an intro/outro of silence -> audio.wav. Records where every clip lands
     on the final timeline.
  2. Pull the words that fall inside each clip from the Whisper JSON, shift
     them onto the timeline, and emit them as spans with CSS animation delays
     so the caption "lights up" word by word as she speaks.
  3. Write the HTML (template lives in this file), render frames with
     capture-animation.js (WAAPI seek => deterministic), mux with the audio.

Usage:
  python3 marketing/tools/build-kinetic-reel.py \
      --audio  scratch/farida/segment.wav \
      --words  scratch/farida/segment.words.json \
      --spec   marketing/assets/poverty-tax-reel.spec.json \
      --out    marketing/assets/export/poverty-tax-reel \
      [--fps 24] [--no-render]

The spec is JSON: {"intro": 1.6, "gap": 0.55, "outro": 13.0, "clips": [
  {"id":"tax","start":435.2,"end":443.4,"eyebrow":"...", "visual":"quote"|"stat"|"route"|"fees", ...}
]}. Times are seconds within --audio.
"""
from __future__ import annotations

import argparse
import html
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent


def sh(*cmd: str) -> None:
    r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if r.returncode != 0:
        sys.exit(f"command failed: {' '.join(cmd)}\n{r.stderr}")


def build_audio(src: Path, spec: dict, out: Path) -> list[dict]:
    """Cut + concat clips. Returns clip list with timeline offsets."""
    out.mkdir(parents=True, exist_ok=True)
    intro, gap, outro = spec["intro"], spec["gap"], spec["outro"]
    parts, timeline, t = [], [], intro
    sil = out / "sil-gap.wav"
    sh("ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "anullsrc=r=48000:cl=mono", "-t", str(gap), sil)
    intro_f = out / "sil-intro.wav"
    sh("ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "anullsrc=r=48000:cl=mono", "-t", str(intro), intro_f)
    outro_f = out / "sil-outro.wav"
    sh("ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "anullsrc=r=48000:cl=mono", "-t", str(outro), outro_f)
    parts.append(intro_f)
    for i, c in enumerate(spec["clips"]):
        dur = c["end"] - c["start"]
        f = out / f"clip-{c['id']}.wav"
        fade = 0.08
        sh("ffmpeg", "-v", "error", "-y", "-ss", str(c["start"]), "-t", str(dur), "-i", str(src),
           "-af", f"afade=t=in:st=0:d={fade},afade=t=out:st={dur - fade}:d={fade},"
                  f"loudnorm=I=-16:TP=-1.5:LRA=11", "-ar", "48000", "-ac", "1", str(f))
        real = float(subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                                     "-of", "csv=p=0", str(f)], capture_output=True, text=True).stdout.strip())
        timeline.append({**c, "t0": round(t, 3), "t1": round(t + real, 3), "dur": round(real, 3)})
        parts.append(f)
        t += real
        if i < len(spec["clips"]) - 1:
            parts.append(sil)
            t += gap
    parts.append(outro_f)
    lst = out / "concat.txt"
    lst.write_text("".join(f"file '{p.resolve()}'\n" for p in parts))
    sh("ffmpeg", "-v", "error", "-y", "-f", "concat", "-safe", "0", "-i", str(lst), "-c:a", "pcm_s16le", str(out / "audio.wav"))
    total = t + outro
    (out / "timeline.json").write_text(json.dumps({"total": round(total, 3), "clips": timeline}, indent=2))
    return timeline, total


def words_for(clip: dict, words: list[dict]) -> list[dict]:
    lo, hi = clip["start"] - 0.05, clip["end"] + 0.05
    sel = [w for w in words if lo <= w["start"] and w["end"] <= hi]
    off = clip["t0"] - clip["start"]
    return [{"w": w["word"].strip(), "t": round(w["start"] + off, 3), "d": round(max(0.12, w["end"] - w["start"]), 3)} for w in sel]


TEMPLATE = r"""<title>The Poverty Tax — Reel</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>
  /* Njangi On-Chain — kinetic-type Reel over interview audio.
     Generated by marketing/tools/build-kinetic-reel.py — edit the template
     there, not this file. Total __TOTAL__s. Single dark theme (MP4 export).
     Every timed element is a CSS animation with an absolute delay so the
     whole piece is seekable via WAAPI currentTime (capture-animation.js). */
  :root {
    --ink:#0a0a0c; --ink-deep:#0d0c12; --ink-surface:#13121a; --ink-border:#2a2620;
    --gold:#E8B04B; --gold-hi:#f6d99a; --cream:#f5f1e8; --sand:#a8a294; --sand-dim:#8b8578;
    --total: __TOTAL__s;
  }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--ink); color:var(--cream); font-family:"IBM Plex Sans",ui-sans-serif,system-ui,sans-serif; display:grid; place-items:center; min-height:100dvh; padding:24px; }
  .frame { width:min(1080px, 92vmin * 9 / 16); aspect-ratio:9/16; position:relative; overflow:hidden; border:1px solid var(--ink-border); border-radius:12px; container-type:inline-size;
    background: radial-gradient(120% 60% at 50% 12%, #14121b 0%, var(--ink-deep) 55%, var(--ink) 100%); }
  /* one scene per clip; visibility keyed by absolute time */
  .scene { position:absolute; inset:0; opacity:0; padding:24cqw 8cqw 32cqw; display:grid; grid-template-rows:auto 1fr auto; animation: show var(--total) linear 1 both; animation-delay:0s; }
  @keyframes show { 0%,100% { opacity:0 } }
  .eyebrow { font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:2cqw; letter-spacing:.22em; text-transform:uppercase; color:var(--gold); margin:0; }
  .who { font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:1.9cqw; letter-spacing:.08em; color:var(--sand-dim); margin:1.2cqw 0 0; }
  .mid { display:grid; align-content:center; gap:5cqw; }
  .cap { margin:0; font-size:6.4cqw; line-height:1.12; letter-spacing:-.025em; font-weight:600; text-wrap:balance; }
  .cap span { color:#3a362f; transition:none; animation: lit var(--total) steps(1) 1 both; }
  @keyframes lit { 0% { color:#3a362f } 100% { color:#3a362f } }
  .cap span.on { color:var(--cream); }
  .cap .k { color:var(--gold) !important; }
  .foot { font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:2cqw; color:var(--sand-dim); letter-spacing:.06em; display:flex; justify-content:space-between; align-self:end; }
  .foot .mark { color:var(--cream); letter-spacing:.14em; text-transform:uppercase; }
  /* visuals */
  .viz { display:grid; place-items:center; }
  .big { font-family:"IBM Plex Sans"; font-weight:600; font-size:26cqw; line-height:.9; letter-spacing:-.05em; color:var(--gold); font-variant-numeric:tabular-nums; margin:0; }
  .big small { display:block; font-size:2.6cqw; letter-spacing:.06em; color:var(--sand); font-weight:400; margin-top:2.4cqw; font-family:"IBM Plex Mono",ui-monospace,monospace; text-transform:uppercase; }
  .bars { width:100%; display:grid; gap:3cqw; }
  .bar { display:grid; grid-template-columns:14cqw 1fr 12cqw; align-items:center; gap:2cqw; font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:2.4cqw; color:var(--sand); }
  .bar i { display:block; height:3.2cqw; background:var(--ink-border); border-radius:2px; position:relative; overflow:hidden; }
  .bar i::after { content:""; position:absolute; inset:0; background:var(--gold); transform-origin:left; transform:scaleX(var(--w)); }
  .bar b { color:var(--cream); font-weight:500; text-align:right; }
  svg { width:84cqw; height:auto; overflow:visible; }
  .lbl { font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:26px; fill:var(--sand); letter-spacing:.12em; text-anchor:middle; }
  .dot { fill:var(--ink-surface); stroke:var(--ink-border); stroke-width:3; }
  .dot.hot { stroke:var(--gold); fill:#241c0c; }
  .route { fill:none; stroke:var(--gold); stroke-width:6; stroke-linecap:round; stroke-dasharray: 1400; stroke-dashoffset:1400; }
  .direct { fill:none; stroke:var(--ink-border); stroke-width:3; stroke-dasharray:8 12; }
  .coin { fill:var(--gold-hi); opacity:0; offset-rotate:0deg; }
  /* ---- the pot cycle (7s), same timings as nobody-holds-the-pot.html.
     Every animation starts at --pot-t0 so the cycle begins with its card. */
  .pot { width:62cqw; height:62cqw; }
  .pot .ring-track { fill:none; stroke:var(--ink-border); stroke-width:2; }
  .pot .ring-fill { fill:none; stroke:var(--gold); stroke-width:6; stroke-linecap:round; stroke-dasharray:880; stroke-dashoffset:880; transform:rotate(-90deg); transform-origin:540px 540px; animation:potfill 7s linear infinite; animation-delay:var(--pot-t0); }
  @keyframes potfill { 0%,8.5%{stroke-dashoffset:880} 8.6%,15.6%{stroke-dashoffset:733} 15.7%,22.8%{stroke-dashoffset:587} 22.9%,29.9%{stroke-dashoffset:440} 30%,37%{stroke-dashoffset:293} 37.1%,44.2%{stroke-dashoffset:147} 44.3%,60%{stroke-dashoffset:0} 78%,100%{stroke-dashoffset:880} }
  .pot .member { fill:var(--ink-surface); stroke:var(--ink-border); stroke-width:2; }
  .pot .member-label { font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:26px; fill:var(--sand-dim); text-anchor:middle; dominant-baseline:central; }
  .pot .recipient .member { animation:potlift 7s ease-in-out infinite; animation-delay:var(--pot-t0); }
  .pot .recipient .member-label { fill:var(--gold-hi); }
  @keyframes potlift { 0%,44%{fill:var(--ink-surface);stroke:var(--ink-border)} 50%,80%{fill:#241c0c;stroke:var(--gold)} 92%,100%{fill:var(--ink-surface);stroke:var(--ink-border)} }
  .pot .contrib { fill:var(--gold); opacity:0; animation:potcontrib 7s ease-in infinite; animation-delay:calc(var(--pot-t0) + var(--stagger)); }
  @keyframes potcontrib { 0%{transform:translate(0,0);opacity:0} 1%{opacity:1} 7.1%{transform:var(--to-centre);opacity:1} 8.5%,100%{transform:var(--to-centre);opacity:0} }
  .pot .payout { fill:var(--gold-hi); opacity:0; animation:potpay 7s cubic-bezier(.4,0,.2,1) infinite; animation-delay:var(--pot-t0); }
  @keyframes potpay { 0%,58%{transform:translate(0,0);opacity:0} 60%{transform:translate(0,0);opacity:1} 76%{transform:var(--to-recipient);opacity:1} 82%,100%{transform:var(--to-recipient);opacity:0} }
  .pot .escrow-well { fill:none; stroke:var(--ink-border); stroke-width:2; stroke-dasharray:6 10; }
  .pot .escrow-cap { font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:24px; fill:var(--sand-dim); text-anchor:middle; letter-spacing:.16em; }
  .pot .escrow-amt { font-family:"IBM Plex Mono",ui-monospace,monospace; font-size:46px; font-weight:500; fill:var(--cream); text-anchor:middle; font-variant-numeric:tabular-nums; opacity:0; animation-duration:7s; animation-timing-function:steps(1); animation-iteration-count:infinite; animation-delay:var(--pot-t0); }
  .pot .amt-0{animation-name:amt0;fill:var(--sand-dim)} .pot .amt-1{animation-name:amt1} .pot .amt-2{animation-name:amt2} .pot .amt-3{animation-name:amt3} .pot .amt-4{animation-name:amt4} .pot .amt-5{animation-name:amt5} .pot .amt-6{animation-name:amt6;fill:var(--gold-hi)}
  @keyframes amt0 { 0%,8.5%{opacity:1} 8.6%,77.9%{opacity:0} 78%,100%{opacity:1} }
  @keyframes amt1 { 0%,8.5%{opacity:0} 8.6%,15.6%{opacity:1} 15.7%,100%{opacity:0} }
  @keyframes amt2 { 0%,15.6%{opacity:0} 15.7%,22.8%{opacity:1} 22.9%,100%{opacity:0} }
  @keyframes amt3 { 0%,22.8%{opacity:0} 22.9%,29.9%{opacity:1} 30%,100%{opacity:0} }
  @keyframes amt4 { 0%,29.9%{opacity:0} 30%,37.0%{opacity:1} 37.1%,100%{opacity:0} }
  @keyframes amt5 { 0%,37.0%{opacity:0} 37.1%,44.2%{opacity:1} 44.3%,100%{opacity:0} }
  @keyframes amt6 { 0%,44.2%{opacity:0} 44.3%,77.9%{opacity:1} 78%,100%{opacity:0} }
  @media (prefers-reduced-motion: reduce) { * { animation: none !important; } .scene { opacity:1 } }
</style>
<div class="frame">
__SCENES__
</div>
<style>
__TIMING__
</style>
"""


def scene_html(c: dict, words: list[dict], idx: int) -> tuple[str, str]:
    """Return (markup, timing css) for one clip scene."""
    sid = f"s{idx}"
    spans = []
    css = []
    for j, w in enumerate(words):
        cls = "k" if w["w"].strip(".,\"'?!").lower() in set(c.get("keywords", [])) else ""
        spans.append(f'<span id="{sid}w{j}" class="{cls}">{html.escape(w["w"])}</span>')
        # word lights up at t and stays lit until the scene ends
        css.append(f"#{sid}w{j}{{animation-name:{sid}w{j}}} @keyframes {sid}w{j}{{0%,{pct(w['t'])}%{{color:#3a362f}} {pct(w['t'] + 0.001)}%,100%{{color:{'var(--gold)' if cls else 'var(--cream)'}}}}}")
    visual = c.get("visual", "quote")
    viz = ""
    if visual == "stat":
        viz = f'<div class="viz"><p class="big">{c["stat"]}<small>{html.escape(c["stat_label"])}</small></p></div>'
    elif visual == "fees":
        viz = ('<div class="viz"><div class="bars">'
               '<div class="bar"><span>Europe</span><i style="--w:.125"></i><b>~2%</b></div>'
               '<div class="bar"><span>Africa</span><i style="--w:1"></i><b>up to 16%</b></div>'
               '</div></div>')
    elif visual == "route":
        viz = ('<div class="viz"><svg viewBox="0 0 900 560" role="img" aria-label="Money from Togo travels to a bank in Europe before reaching neighbouring Ghana.">'
               '<path class="direct" d="M 300 430 L 600 430"/>'
               '<path class="route" d="M 300 430 C 300 120, 600 120, 600 430"/>'
               '<circle class="dot" cx="300" cy="430" r="34"/><text class="lbl" x="300" y="510">TOGO</text>'
               '<circle class="dot" cx="600" cy="430" r="34"/><text class="lbl" x="600" y="510">GHANA</text>'
               '<circle class="dot hot" cx="450" cy="200" r="34"/><text class="lbl" x="450" y="150">A BANK IN EUROPE</text>'
               '<circle class="coin" r="14" style="offset-path: path(\'M 300 430 C 300 120, 600 120, 600 430\')"/>'
               '</svg></div>')
        # route draws + coin travels during the clip
        a, b = c["t0"] + 1.0, c["t1"] - 0.6
        css.append(f".{sid} .route{{animation:{sid}route var(--total) linear 1 both}} @keyframes {sid}route{{0%,{pct(a)}%{{stroke-dashoffset:1400}} {pct(b)}%,100%{{stroke-dashoffset:0}}}}")
        css.append(f".{sid} .coin{{animation:{sid}coin var(--total) linear 1 both}} @keyframes {sid}coin{{0%,{pct(a)}%{{offset-distance:0%;opacity:0}} {pct(a + 0.05)}%{{opacity:1}} {pct(b)}%{{offset-distance:100%;opacity:1}} {pct(b + 0.05)}%,100%{{offset-distance:100%;opacity:0}}}}")
    if visual == "fees":
        a, b = c["t0"] + 0.8, c["t1"] - 1.0
        css.append(f".{sid} .bar i::after{{transform:scaleX(0);animation:{sid}bar var(--total) cubic-bezier(.4,0,.2,1) 1 both}} @keyframes {sid}bar{{0%,{pct(a)}%{{transform:scaleX(0)}} {pct(b)}%,100%{{transform:scaleX(var(--w))}}}}")
    if visual == "stat":
        a = c["t0"] + float(c.get("stat_at", 0.8))
        css.append(f".{sid} .big{{opacity:0;transform:translateY(3cqw);animation:{sid}stat var(--total) cubic-bezier(.2,.7,.2,1) 1 both}} @keyframes {sid}stat{{0%,{pct(a)}%{{opacity:0;transform:translateY(3cqw)}} {pct(a + 0.5)}%,100%{{opacity:1;transform:translateY(0)}}}}")
    n = len(words)
    cap_size = "6.4cqw" if n <= 22 else "5.6cqw" if n <= 34 else "4.9cqw"
    markup = (f'<section class="scene {sid}">'
              f'<div><p class="eyebrow">{html.escape(c["eyebrow"])}</p><p class="who">{html.escape(c.get("who", "Farida Nabourema, in her own words"))}</p></div>'
              f'<div class="mid">{viz}<p class="cap" style="font-size:{cap_size}">{" ".join(spans)}</p></div>'
              f'<div class="foot"><span class="mark">Njangi On-Chain</span><span>{html.escape(c.get("foot", "source in comments"))}</span></div>'
              f'</section>')
    # scene visibility window (short fades)
    f = 0.35
    css.append(f".{sid}{{animation-name:{sid}show}} @keyframes {sid}show{{0%,{pct(c['t0'] - f)}%{{opacity:0}} {pct(c['t0'])}%,{pct(c['t1'])}%{{opacity:1}} {pct(c['t1'] + f)}%,100%{{opacity:0}}}}")
    return markup, "\n".join(css)


TOTAL = 1.0


def pct(t: float) -> str:
    return f"{max(0.0, min(100.0, 100.0 * t / TOTAL)):.3f}"


def cards_html(o: list[dict], t0: float, t1: float, prefix: str = "o") -> tuple[str, str]:
    """Text cards over a time window (intro credit, outro). Pure CSS, keyed to time."""
    css = []
    marks = []
    weights = [float(c.get("dur", 1.0)) for c in o]
    scale = (t1 - t0) / sum(weights)
    a = t0
    for i, card in enumerate(o):
        b = a + weights[i] * scale
        sid = f"{prefix}{i}"
        viz = ""
        if card.get("viz") == "pot":
            viz = (f'<div class="viz" style="--pot-t0:{a + 0.4:.3f}s"><svg class="pot" viewBox="0 0 1080 1080" role="img" aria-label="Six members pay into a shared pot; the full pot then moves to one scheduled member.">'
                   '<circle class="ring-track" cx="540" cy="540" r="140"/><circle class="ring-fill" cx="540" cy="540" r="140"/>'
                   '<circle class="escrow-well" cx="540" cy="540" r="96"/><text class="escrow-cap" x="540" y="516">THE POT</text>'
                   + "".join(f'<text class="escrow-amt amt-{k}" x="540" y="574">{k} / 6</text>' for k in range(7)) +
                   '<g class="node"><g transform="translate(540,180)"><circle class="member" r="52"/><text class="member-label" y="2">1</text></g></g>'
                   '<g class="node recipient"><g transform="translate(852,360)"><circle class="member" r="52"/><text class="member-label" y="2">2</text></g></g>'
                   '<g class="node"><g transform="translate(852,720)"><circle class="member" r="52"/><text class="member-label" y="2">3</text></g></g>'
                   '<g class="node"><g transform="translate(540,900)"><circle class="member" r="52"/><text class="member-label" y="2">4</text></g></g>'
                   '<g class="node"><g transform="translate(228,720)"><circle class="member" r="52"/><text class="member-label" y="2">5</text></g></g>'
                   '<g class="node"><g transform="translate(228,360)"><circle class="member" r="52"/><text class="member-label" y="2">6</text></g></g>'
                   '<circle class="contrib" r="13" cx="540" cy="180" style="--to-centre:translate(0px,300px);--stagger:.1s"/>'
                   '<circle class="contrib" r="13" cx="852" cy="360" style="--to-centre:translate(-260px,150px);--stagger:.6s"/>'
                   '<circle class="contrib" r="13" cx="852" cy="720" style="--to-centre:translate(-260px,-150px);--stagger:1.1s"/>'
                   '<circle class="contrib" r="13" cx="540" cy="900" style="--to-centre:translate(0px,-300px);--stagger:1.6s"/>'
                   '<circle class="contrib" r="13" cx="228" cy="720" style="--to-centre:translate(260px,-150px);--stagger:2.1s"/>'
                   '<circle class="contrib" r="13" cx="228" cy="360" style="--to-centre:translate(260px,150px);--stagger:2.6s"/>'
                   '<circle class="payout" r="22" cx="540" cy="540" style="--to-recipient:translate(312px,-180px)"/>'
                   '</svg></div>')
        marks.append(f'<section class="scene {sid}"><div><p class="eyebrow">{html.escape(card["eyebrow"])}</p></div>'
                     f'<div class="mid">{viz}<p class="cap"><span style="animation:none;color:var(--cream)">{card["h"]}</span></p>'
                     f'{("<p class=\"who\" style=\"font-size:2.6cqw;color:var(--sand);letter-spacing:0;line-height:1.45;max-width:34ch\">" + html.escape(card["sub"]) + "</p>") if card.get("sub") else ""}</div>'
                     f'<div class="foot"><span class="mark">Njangi On-Chain</span><span>{html.escape(card.get("foot", "njangionchain.com · link in bio"))}</span></div></section>')
        f = 0.35
        css.append(f".{sid}{{animation-name:{sid}show}} @keyframes {sid}show{{0%,{pct(a - f)}%{{opacity:0}} {pct(a)}%,{pct(b - f)}%{{opacity:1}} {pct(b)}%,100%{{opacity:0}}}}")
        a = b
    return "\n".join(marks), "\n".join(css)


def main() -> int:
    global TOTAL
    ap = argparse.ArgumentParser()
    ap.add_argument("--audio", required=True)
    ap.add_argument("--words", required=True)
    ap.add_argument("--spec", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--fps", type=int, default=24)
    ap.add_argument("--no-render", action="store_true")
    a = ap.parse_args()

    spec = json.loads(Path(a.spec).read_text())
    wj = json.loads(Path(a.words).read_text())
    words = [w for s in wj["segments"] for w in s.get("words", [])]
    out = Path(a.out)
    timeline, total = build_audio(Path(a.audio), spec, out)
    TOTAL = total

    scenes, css = [], []
    for i, c in enumerate(timeline):
        m, t = scene_html(c, words_for(c, words), i)
        scenes.append(m)
        css.append(t)
    last_end = timeline[-1]["t1"] + 0.4
    m, t = cards_html(spec["outro_cards"], last_end, total - 0.3, "o")
    scenes.append(m)
    css.append(t)
    if spec.get("intro_cards"):
        m, t = cards_html(spec["intro_cards"], 0.15, spec["intro"] - 0.25, "i")
        scenes.append(m)
        css.append(t)

    page = (TEMPLATE.replace("__TOTAL__", f"{total:.3f}")
            .replace("__SCENES__", "\n".join(scenes))
            .replace("__TIMING__", "\n".join(css)))
    html_path = ROOT / "marketing" / "assets" / f"{spec['name']}.html"
    html_path.write_text(page)
    print(f"html -> {html_path}  total {total:.2f}s")
    for c in timeline:
        print(f"  {c['id']:<8} {c['t0']:6.2f} -> {c['t1']:6.2f}  ({c['dur']:.2f}s)")
    if a.no_render:
        return 0

    frames = out / "frames"
    if frames.exists():
        for f in frames.glob("*.png"):
            f.unlink()
    sh("node", str(HERE / "capture-animation.js"), "--in", str(html_path), "--out", str(frames),
       "--width", "1080", "--height", "1920", "--seconds", f"{total:.3f}", "--fps", str(a.fps))
    mp4 = out / f"{spec['name']}.mp4"
    sh("ffmpeg", "-v", "error", "-y", "-framerate", str(a.fps), "-i", str(frames / "f%04d.png"),
       "-i", str(out / "audio.wav"), "-c:v", "libx264", "-profile:v", "high", "-level", "4.1", "-preset", "slow",
       "-crf", "18", "-pix_fmt", "yuv420p", "-r", str(a.fps), "-c:a", "aac", "-b:a", "160k", "-shortest",
       "-movflags", "+faststart", str(mp4))
    print(f"mp4 -> {mp4}")
    for f in frames.glob("*.png"):
        f.unlink()
    frames.rmdir()
    return 0


if __name__ == "__main__":
    sys.exit(main())
