#!/usr/bin/env node
// bootstrap-package.mjs — Post-publish bootstrap for a fresh Move
// package on Sui testnet/mainnet. Closes the gap where build_and_test.sh
// captures the package id but leaves three other object ids dangling for
// the operator to discover manually.
//
// What it does (idempotent, safe to re-run):
//   1. Walks the publish transaction's `objectChanges` to locate the
//      `AttestorCap` object that `njangi_compliance::init` minted. Writes
//      `NEXT_PUBLIC_<NETWORK>_NJANGI_ATTESTOR_CAP_ID` and the public
//      `NEXT_PUBLIC_NJANGI_ATTESTATION_ISSUER` (the cap-holder address).
//   2. Calls `whatsapp_integration::init_registry` (skip if the env var
//      already points at a live shared object on this network).
//   3. Calls `njangi_price_validator::init_registry`. Same skip rule.
//   4. Patches `.env.local` with all three object ids without touching
//      anything else.
//
// Usage:
//   NJANGI_BOOTSTRAP_NETWORK=testnet \
//   NJANGI_BOOTSTRAP_GAS_BUDGET=200000000 \
//   node scripts/bootstrap-package.mjs <packageId>
//
//   or via npm: npm run bootstrap:package -- <packageId>
//
// Env knobs:
//   NJANGI_BOOTSTRAP_NETWORK  testnet | mainnet (default: testnet)
//   NJANGI_BOOTSTRAP_GAS_BUDGET  default 200000000
//   NJANGI_BOOTSTRAP_ENV_FILE  override .env.local path

import { execFile, execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import process from 'node:process';

const exec = promisify(execFile);
const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const PACKAGE_ID = process.argv[2];
if (!PACKAGE_ID || !/^0x[a-fA-F0-9]+$/.test(PACKAGE_ID)) {
  console.error('[bootstrap] usage: node scripts/bootstrap-package.mjs <packageId>');
  process.exit(1);
}

const NETWORK = (process.env.NJANGI_BOOTSTRAP_NETWORK || 'testnet').toLowerCase();
if (NETWORK !== 'testnet' && NETWORK !== 'mainnet') {
  console.error(`[bootstrap] unsupported network: ${NETWORK}`);
  process.exit(1);
}

const GAS_BUDGET = process.env.NJANGI_BOOTSTRAP_GAS_BUDGET || '200000000';
const ENV_FILE =
  process.env.NJANGI_BOOTSTRAP_ENV_FILE
    ? resolve(process.cwd(), process.env.NJANGI_BOOTSTRAP_ENV_FILE)
    : resolve(repoRoot, '.env.local');

const NETWORK_UPPER = NETWORK.toUpperCase();
const ENV_KEYS = {
  attestorCap: `NEXT_PUBLIC_${NETWORK_UPPER}_NJANGI_ATTESTOR_CAP_ID`,
  attestorIssuer: 'NEXT_PUBLIC_NJANGI_ATTESTATION_ISSUER',
  whatsappRegistry: `NEXT_PUBLIC_${NETWORK_UPPER}_WHATSAPP_REGISTRY_ID`,
  assetRegistry: `NEXT_PUBLIC_${NETWORK_UPPER}_NJANGI_ASSET_REGISTRY_ID`,
};

const STRUCT_TYPES = {
  attestorCap: `${PACKAGE_ID}::njangi_compliance::AttestorCap`,
  whatsappRegistry: `${PACKAGE_ID}::whatsapp_integration::WhatsAppLinksRegistry`,
  assetRegistry: `${PACKAGE_ID}::njangi_price_validator::AssetRegistry`,
};

function log(message) {
  console.log(`[bootstrap] ${message}`);
}

function ensureEnvFile() {
  if (existsSync(ENV_FILE)) return;
  console.error(`[bootstrap] env file missing: ${ENV_FILE}`);
  console.error('[bootstrap] cp .env.example .env.local first.');
  process.exit(1);
}

function readEnv() {
  const content = readFileSync(ENV_FILE, 'utf8');
  const map = new Map();
  for (const line of content.split(/\r?\n/)) {
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    map.set(line.slice(0, eq).trim(), line.slice(eq + 1).trim());
  }
  return { content, map };
}

function patchEnv(updates) {
  if (updates.size === 0) return;
  let { content } = readEnv();
  const additions = [];
  for (const [key, value] of updates) {
    const re = new RegExp(`^${key}=.*$`, 'm');
    if (re.test(content)) {
      content = content.replace(re, `${key}=${value}`);
    } else {
      additions.push(`${key}=${value}`);
    }
  }
  if (additions.length > 0) {
    if (!content.endsWith('\n')) content += '\n';
    content +=
      '\n# Generated by scripts/bootstrap-package.mjs ' +
      new Date().toISOString() +
      '\n' +
      additions.join('\n') +
      '\n';
  }
  writeFileSync(ENV_FILE, content, 'utf8');
}

async function suiCallJson(args) {
  // Wraps `sui client` with `--json` so we always get structured output.
  const cmd = ['client', ...args, '--json'];
  try {
    const { stdout } = await exec('sui', cmd, { cwd: repoRoot, maxBuffer: 32 * 1024 * 1024 });
    return JSON.parse(stdout);
  } catch (err) {
    const stderr = err && typeof err === 'object' && 'stderr' in err ? err.stderr : err;
    throw new Error(`sui ${cmd.join(' ')} failed: ${stderr}`);
  }
}

async function activeAddress() {
  try {
    const out = execFileSync('sui', ['client', 'active-address'], {
      cwd: repoRoot,
      encoding: 'utf8',
    });
    return out.trim();
  } catch (err) {
    throw new Error(`sui client active-address failed: ${err}`);
  }
}

const RPC_URL =
  process.env.NJANGI_BOOTSTRAP_RPC_URL ||
  (NETWORK === 'mainnet'
    ? 'https://fullnode.mainnet.sui.io:443'
    : 'https://fullnode.testnet.sui.io:443');

async function rpcCall(method, params) {
  const res = await fetch(RPC_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }),
  });
  if (!res.ok) throw new Error(`rpc ${method} http ${res.status}`);
  const json = await res.json();
  if (json.error) throw new Error(`rpc ${method} error: ${JSON.stringify(json.error)}`);
  return json.result;
}

async function getOwnedObject(owner, structType) {
  // Sui CLI 1.69 dropped `--filter`, so query the fullnode RPC directly.
  const result = await rpcCall('suix_getOwnedObjects', [
    owner,
    { filter: { StructType: structType }, options: { showType: true } },
    null,
    50,
  ]);
  const data = result?.data ?? [];
  for (const item of data) {
    const objectId = item?.data?.objectId;
    if (objectId) return objectId;
  }
  return null;
}

async function getSharedObject(structType) {
  // Sui RPC doesn't expose a direct "list every shared object of type T"
  // call, so we rely on the publish output (passed in via env) when
  // available, or fall back to an event-based discovery via the package
  // events. For init_registry we created a fresh shared object inside
  // the call's effects, so the safer path is to inspect the call
  // response itself — handled by callMoveAndCaptureSharedObject below.
  void structType;
  return null;
}

async function callMoveAndCaptureSharedObject(target, structType) {
  log(`calling ${target}`);
  const result = await suiCallJson([
    'call',
    '--package',
    PACKAGE_ID,
    '--module',
    target.module,
    '--function',
    target.fn,
    '--gas-budget',
    GAS_BUDGET,
  ]);
  const changes = result?.objectChanges ?? [];
  for (const change of changes) {
    if (change?.type === 'created' && change?.objectType === structType) {
      return change.objectId;
    }
  }
  // Some CLI versions nest the changes under effects.
  const effects = result?.effects?.created ?? [];
  for (const change of effects) {
    if (change?.reference?.objectId && change?.owner?.Shared) {
      return change.reference.objectId;
    }
  }
  return null;
}

async function captureAttestorCap(deployer) {
  // The compliance module's `init` transferred the cap to the deployer.
  // We try the owner's object set first; if the operator already moved
  // the cap to a multisig, env can be patched manually after the fact.
  log(`looking up AttestorCap owned by ${deployer}`);
  const objectId = await getOwnedObject(deployer, STRUCT_TYPES.attestorCap);
  if (!objectId) {
    log('AttestorCap not found in deployer wallet — set the env var manually if it was already transferred.');
    return null;
  }
  log(`AttestorCap = ${objectId}`);
  return objectId;
}

async function ensureRegistry(structType, target) {
  const updates = new Map();
  const { map } = readEnv();
  const envKey = target.envKey;
  const existing = map.get(envKey);
  if (existing && existing.startsWith('0x')) {
    log(`${envKey} already set; skipping ${target.module}::${target.fn}`);
    return { id: existing, updates };
  }
  // No prior id: try a discovery first (in case the call ran but the env
  // wasn't captured), otherwise execute the init call.
  const discovered = await getSharedObject(structType);
  if (discovered) {
    log(`discovered ${structType} = ${discovered}`);
    updates.set(envKey, discovered);
    return { id: discovered, updates };
  }
  const created = await callMoveAndCaptureSharedObject(target, structType);
  if (!created) {
    log(`could not capture object id from ${target.module}::${target.fn} response`);
    return { id: null, updates };
  }
  log(`${structType} = ${created}`);
  updates.set(envKey, created);
  return { id: created, updates };
}

async function main() {
  ensureEnvFile();

  log(`network=${NETWORK}  package=${PACKAGE_ID}  env=${ENV_FILE.replace(repoRoot + '/', '')}`);

  const updates = new Map();
  const deployer = await activeAddress();
  log(`deployer=${deployer}`);

  // 1. AttestorCap (auto-minted by njangi_compliance::init at publish)
  const capId = await captureAttestorCap(deployer);
  if (capId) {
    updates.set(ENV_KEYS.attestorCap, capId);
    updates.set(ENV_KEYS.attestorIssuer, deployer);
  }

  // 2. WhatsAppLinksRegistry
  const wa = await ensureRegistry(STRUCT_TYPES.whatsappRegistry, {
    module: 'whatsapp_integration',
    fn: 'init_registry',
    envKey: ENV_KEYS.whatsappRegistry,
  });
  for (const [k, v] of wa.updates) updates.set(k, v);

  // 3. AssetRegistry (oracle config)
  const asset = await ensureRegistry(STRUCT_TYPES.assetRegistry, {
    module: 'njangi_price_validator',
    fn: 'init_registry',
    envKey: ENV_KEYS.assetRegistry,
  });
  for (const [k, v] of asset.updates) updates.set(k, v);

  patchEnv(updates);
  log(`patched ${updates.size} env entries`);
  log('next: run npm run validate:env then npm run smoke:testnet');
}

main().catch((err) => {
  console.error('[bootstrap] fatal', err);
  process.exit(1);
});
