#!/usr/bin/env node
// generate-secrets.mjs — Generate any missing 32-byte hex secrets and
// patch them into `.env.local` (or the file passed as argv[2]). Existing
// values are never overwritten, so re-running is safe.
//
// Generated keys:
//   * WALRUS_PII_MASTER_KEY        — AES-256 master for PII envelopes
//   * WALRUS_LOOKUP_SALT           — HMAC salt for whatsapp phone index
//   * COMPLIANCE_REF_HMAC_SALT     — HMAC salt for ramp case ids
//   * INTERNAL_NOTIFY_SECRET       — shared secret for notifier + console
//   * COMPLIANCE_ISSUANCE_SECRET   — distinct secret for /api/compliance/*
//                                    (falls back to INTERNAL_NOTIFY_SECRET
//                                    when unset, but the audit team likes
//                                    to see them split, so we generate
//                                    both by default).
//   * ZKLOGIN_SESSION_ENC_KEY      — AES-256 key encrypting zkLogin session
//                                    payloads (ephemeral keys + zk proofs)
//                                    at rest in the Postgres
//                                    `zklogin_sessions` table.
//   * CRON_SECRET                  — bearer secret Vercel attaches to cron
//                                    invocations (/api/cron/*). Must match
//                                    the env var set on the Vercel project.
//   * LEGAL_ACCEPT_IP_SALT         — HMAC salt for hashing client IPs on
//                                    legal-acceptance / data-deletion rows
//                                    (raw IPs are never stored; see
//                                    docs/legal-drafts/ACCEPTANCE-GATE-SPEC.md).
//
// Usage:
//   node scripts/generate-secrets.mjs           # patches .env.local
//   node scripts/generate-secrets.mjs path/to/.env.testnet
//   npm run generate:secrets

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import process from 'node:process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const SECRET_KEYS = [
  'WALRUS_PII_MASTER_KEY',
  'WALRUS_LOOKUP_SALT',
  'COMPLIANCE_REF_HMAC_SALT',
  'INTERNAL_NOTIFY_SECRET',
  'COMPLIANCE_ISSUANCE_SECRET',
  'ZKLOGIN_SESSION_ENC_KEY',
  'CRON_SECRET',
  'LEGAL_ACCEPT_IP_SALT',
];

function defaultEnvPath() {
  return resolve(repoRoot, '.env.local');
}

function pickEnvPath() {
  const arg = process.argv[2];
  if (arg) return resolve(process.cwd(), arg);
  return defaultEnvPath();
}

function parseEnv(content) {
  const result = new Map();
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    result.set(key, value);
  }
  return result;
}

function applyAdditions(content, additions) {
  // Append missing keys without disturbing existing layout. Existing
  // entries with empty values get overwritten (single occurrence
  // replacement); brand-new keys get appended in a clearly-marked block.
  let out = content;
  const trailing = out.endsWith('\n') ? '' : '\n';
  const additionsBlock = [];
  for (const [key, value] of additions) {
    const inline = new RegExp(`^${key}=$`, 'm');
    if (inline.test(out)) {
      out = out.replace(inline, `${key}=${value}`);
      continue;
    }
    additionsBlock.push(`${key}=${value}`);
  }
  if (additionsBlock.length === 0) {
    return out;
  }
  return (
    out +
    trailing +
    '\n# Generated by scripts/generate-secrets.mjs ' +
    new Date().toISOString() +
    '\n' +
    additionsBlock.join('\n') +
    '\n'
  );
}

function main() {
  const envPath = pickEnvPath();
  if (!existsSync(envPath)) {
    console.error(`[secrets] env file not found: ${envPath}`);
    console.error('[secrets] cp .env.example .env.local first.');
    process.exit(1);
  }
  const content = readFileSync(envPath, 'utf8');
  const existing = parseEnv(content);

  const additions = new Map();
  for (const key of SECRET_KEYS) {
    const current = existing.get(key);
    if (current && current.length > 0) {
      console.log(`[secrets] keep ${key} (already set)`);
      continue;
    }
    const next = randomBytes(32).toString('hex');
    additions.set(key, next);
    console.log(`[secrets] add  ${key} (32 bytes)`);
  }

  if (additions.size === 0) {
    console.log('[secrets] nothing to do — all keys already set.');
    return;
  }

  const updated = applyAdditions(content, additions);
  writeFileSync(envPath, updated, 'utf8');
  console.log(
    `[secrets] wrote ${additions.size} new key(s) to ${envPath.replace(repoRoot + '/', '')}`,
  );
  console.log('[secrets] next step: re-run npm run validate:env');
}

main();
